# .bashrc
alias vim=vimx
alias vi=vimx

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

if [ -f $(which powerline-daemon) ]; then
    powerline-daemon -q
    POWERLINE_BASH_CONTINUATION=1
    POWERLINE_BASE_SELECT=1
    . /usr/share/powerline/bash/powerline.sh
fi

# User specific aliases and functions
tmux attach &> /dev/null
[ -z "$TMUX" ] && tmux

[[ ! -e "$HOME/.cargo" ]] && curl https://sh.rustup.rs -sSf | sh && source "$HOME/.cargo/env"

export NVM_DIR="$HOME/.nvm"
[ ! -e $NVM_DIR ] && curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.1/install.sh 2> /dev/null | bash
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
[[ $(nvm version) == "none" ]] && nvm install lts/carbon

[ -f ~/.fzf.bash ] && source ~/.fzf.bash
export FZF_DEFAULT_COMMAND='rg --files --no-ignore --hidden --follow -g "!{.git,node_modules,js}/*" 2> /dev/null'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
bind -x '"\C-p": vim $(fzf);'
